version: "3.8"
 
services:
  db:
    container_name: lego_parser_db
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"

  web:
    container_name: lego_parser_app
    image: lego-parser
    build: .
    command: gunicorn lego.wsgi:application --bind 0.0.0.0:8000 --timeout 200
    volumes:
      - .:/lego-parser
      - static:/lego/staticfiles/
      - media:/lego/mediafiles/
    ports:
    - "8001:8000"
    env_file:
      - ./.dev.env
      - ./.celery.env
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A lego worker -l INFO
    entrypoint: [ "/lego/entrypoint.sh" ]
    env_file:
      - ./.dev.env
      - ./.celery.env
    depends_on:
      - redis

  nginx:
    container_name: parser_lego
    build: ./nginx
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres:
  static:
  media: